from __future__ import annotations

"""
Large Codebase Planning Agent.

Role in Pipeline:
This agent runs sequentially after the ingestion phase completes.
It evaluates the `module_map` generated by the `ingestion_agent` and assigns specific modules
to each expert in the fleet (`quality_expert`, `security_expert`, etc.).
This strategic division of labor prevents context window saturation when auditing massive codebases.

State Interactions:
- Reads: `is_large_codebase`, `module_map`, `user_request`
- Writes: `review_plan` (A structured JSON adhering to the `ReviewPlan` schema)
"""

import logging
from google.adk.agents import LlmAgent
from google.adk.agents.callback_context import CallbackContext
from ..config import Config
from ..prompts import PLANNING_AGENT_PROMPT
from ..models.planning import ReviewPlan
from ..utils.json_parse import parse_json_into_model
from ..utils.markdown_format import format_review_plan_md

logger = logging.getLogger(__name__)
_cfg = Config()


def _planning_after_callback(callback_context: CallbackContext):
    """
    Parses the ReviewPlan JSON from state and stores it so experts can
    read their assignments. On any failure (empty output, malformed JSON,
    schema mismatch) writes a deterministic fallback so downstream experts
    never receive corrupted JSON or an empty key.
    """
    fallback_plan = {
        "is_large_codebase": bool(callback_context.state.get("is_large_codebase", False)),
        "strategy": "FALLBACK: planning_agent failed; every expert reviews all modules.",
        "assignments": [
            {
                "expert_name": expert,
                "assigned_modules": ["all"],
                "focus_areas": "Review all available code (planning fallback).",
            }
            for expert in (
                "quality_expert",
                "security_expert",
                "governance_expert",
                "adk_expert",
            )
        ],
    }

    raw = callback_context.state.get("review_plan", "")
    if not raw:
        logger.warning(
            "planning_agent: no output found in state['review_plan']. "
            "Installing fallback plan (all_experts_review_all)."
        )
        callback_context.state["review_plan"] = fallback_plan
        md_text = format_review_plan_md(fallback_plan)
        callback_context.state["review_plan_md"] = md_text
        return None

    plan = parse_json_into_model(raw, ReviewPlan, context="planning_agent")
    if plan is None:
        callback_context.state["review_plan"] = fallback_plan
        md_text = format_review_plan_md(fallback_plan)
        callback_context.state["review_plan_md"] = md_text
        return None

    # Validate assigned modules against module_map; reassign unknowns to "all".
    module_map = callback_context.state.get("module_map", {}) or {}
    if isinstance(module_map, dict) and module_map:
        valid_modules = set(module_map.keys())
        for assignment in plan.assignments:
            bad = [m for m in assignment.assigned_modules if m != "all" and m not in valid_modules]
            if bad:
                logger.warning(
                    f"planning_agent: expert {assignment.expert_name} "
                    f"assigned unknown modules {bad}; reassigning to ['all']."
                )
                assignment.assigned_modules = ["all"]

    logger.info(
        f"planning_agent: Plan created with strategy '{plan.strategy}' and {len(plan.assignments)} assignments."
    )

    plan_dict = plan.model_dump()
    callback_context.state["review_plan"] = plan_dict
    md_text = format_review_plan_md(plan_dict)
    callback_context.state["review_plan_md"] = md_text
    return None


planning_agent = LlmAgent(
    model=_cfg.agent_settings.expert_model,
    name="planning_agent",
    description="Analyzes large codebases and assigns specific modules to expert reviewers.",
    instruction=PLANNING_AGENT_PROMPT,
    output_key="review_plan",
    output_schema=ReviewPlan,
    include_contents="none",
    generate_content_config=_cfg.safety_config,
    after_agent_callback=_planning_after_callback,
)
